# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Performance SpannerIO Write 2GB Test Python

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '30 3,15 * * *'
  workflow_dispatch:

#Setting explicit permissions for the action to avoid the default permissions which are `write-all` in case of pull_request_target event
permissions:
  actions: write
  pull-requests: write
  checks: write
  contents: read
  deployments: read
  id-token: none
  issues: write
  discussions: read
  packages: read
  pages: read
  repository-projects: read
  security-events: read
  statuses: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule || github.event.comment.body || github.event.sender.login }}'
  cancel-in-progress: true

env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}

jobs:
  beam_PerformanceTests_SpannerIO_Write_2GB_Python:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      github.event.comment.body == 'Run SpannerIO Write 2GB Performance Test Python'
    runs-on: [self-hosted, ubuntu-20.04, main]
    timeout-minutes: 480
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    strategy:
      matrix:
        job_name: ["beam_PerformanceTests_SpannerIO_Write_2GB_Python"]
        job_phrase: ["Run SpannerIO Write 2GB Performance Test Python"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup repository
        uses: ./.github/actions/setup-action
        with:
          comment_phrase: ${{ matrix.job_phrase }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Sleep
        run: sleep 3600
      - name: run Performance SpannerIO Write 2GB Test Python
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :sdks:python:apache_beam:testing:load_tests:run
          arguments: |
            -PloadTest.mainClass=apache_beam.io.gcp.experimental.spannerio_write_perf_test \
            -Prunner=DataflowRunner \
            -PpythonVersion=3.8 \
            '-PloadTest.args=--job_name=performance-tests-spannerio-write-python-batch-2gb0918164440 --project=apache-beam-testing --region=us-west1 --temp_location=gs://temp-storage-for-perf-tests/loadtests --spanner_instance=beam-test --spanner_database=pyspanner_write_2gb --publish_to_big_query=true --metrics_dataset=beam_performance --metrics_table=pyspanner_write_2GB_results --influx_measurement=python_spanner_write_2GB_results --influx_db_name=beam_test_metrics --influx_hostname=http://10.128.0.96:8086 --input_options=''{\\"num_records\\":2097152,\\"key_size\\":1,\\"value_size\\":1024,\\"algorithm\\":\\"lcg\\"}'' --num_****s=5 --autoscaling_algorithm=NONE --runner=DataflowRunner'