# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Performance Java KafkaIO Test

on:
  schedule:
    - cron: '30 2,14 * * *'
  workflow_dispatch:

#Setting explicit permissions for the action to avoid the default permissions which are `write-all` in case of pull_request_target event
permissions:
  actions: write
  pull-requests: write
  checks: write
  contents: read
  deployments: read
  id-token: none
  issues: write
  discussions: read
  packages: read
  pages: read
  repository-projects: read
  security-events: read
  statuses: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.issue.number || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule || github.event.comment.body || github.event.sender.login }}'
  cancel-in-progress: true

env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}

jobs:
  beam_PerformanceTests_Kafka_IO:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      github.event.comment.body == 'Run Java KafkaIO Performance Test'
    runs-on: [self-hosted, ubuntu-20.04, main]
    timeout-minutes: 120
    name: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
    strategy:
      matrix:
        job_name: ["beam_PerformanceTests_Kafka_IO"]
        job_phrase: ["Run Java KafkaIO Performance Test"]
    env:
      KAFKA_SERVICE_PORT_0: 0
      KAFKA_SERVICE_PORT_1: 0
      KAFKA_SERVICE_PORT_2: 0
      KAFKA_SERVICE_PORT_3: 0
    steps:
      - uses: actions/checkout@v3
      - name: Setup repository
        uses: ./.github/actions/setup-action
        with:
          comment_phrase: ${{ matrix.job_phrase }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_job: ${{ matrix.job_name }} (${{ matrix.job_phrase }})
      - name: Set k8s access
        uses: ./.github/actions/setup-k8s-access
        with:
          cluster_name: io-datastores
          k8s_namespace: ${{ matrix.job_name }}-${{ github.run_id }}
      - name: Install Kafka
        id: install_kafka
        run: |
          cd ${{ github.workspace }}/.test-infra/kubernetes/kafka-cluster/
          kubectl apply -R -f .
      - name: Set up Kafka service ports
        id: set_ports
        shell: bash
        run: |
          configuredPorts=(32400 32401 32402)
          HIGH_RANGE_PORT=32767
          declare -a kafka_service_ports  
          for service in {0..2}; do
            new_port=0
            if [ $service -eq 0 ]; then
              new_port=${configuredPorts[$service]}
            else
              previous_service=$((service - 1))
              new_port=${kafka_service_ports[$previous_service]}
            fi
            input=$(.test-infra/kubernetes/kubernetes.sh getAvailablePort ${new_port} ${HIGH_RANGE_PORT})
            KAFKA_SERVICE_PORT_0=$(echo "$input" | head -n 1 | sed 's/:$//')
            # Print the extracted and modified variable
            echo "KAFKA_SERVICE_PORT_0=$KAFKA_SERVICE_PORT_0"
            sed -i -e 's/${configuredPorts[$service]}/${KAFKA_SERVICE_PORT_${service}}/' ${{ github.workspace }}/.test-infra/kubernetes/kafka-cluster/04-outside-services/outside-${service}.yml
          done
      - name: Set up Kafka brokers
        id: set_brokers
        run: |
          declare -a kafka_service_brokers
          for INDEX in {0..2}; do
            kubectl wait svc/outside-${INDEX} --for=jsonpath='{.status.loadBalancer.ingress[0].ip}' --timeout=40m
            kafka_service_brokers[$INDEX]=$(kubectl get svc outside-${INDEX} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            echo "KAFKA_SERVICE_BROKER_${INDEX}=${kafka_service_brokers[$INDEX]}" >> $GITHUB_OUTPUT
          done
      - name: Prepare config
        id: set_config
        shell: bash
        run: |
          CURDATE=$(date '+%m%d%H%M%S' --utc)
          CURCONFIG=$(grep -v "^#.*" ./.github/workflows/performance-tests-job-configs/config_Kafka_IO.txt | tr '\n' ' ')
          CONFIGWITHDATE=$(echo "${CURCONFIG/kafka_io_/kafka_io_$CURDATE}")
          echo "prepared_config=$CONFIGWITHDATE" >> $GITHUB_OUTPUT
      - name: Run Java KafkaIO Performance Test 1
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :sdks:java:io:kafka:integrationTest
          arguments: |
            --tests org.apache.beam.sdk.io.kafka.KafkaIOIT.testKafkaIOReadsAndWritesCorrectlyInStreaming \
            --info \
            -DintegrationTestRunner=dataflow \
            -DintegrationTestPipelineOptions='[${{ steps.set_config.outputs.prepared_config }}"--kafkaBootstrapServerAddresses=${{ steps.set_brokers.outputs.KAFKA_SERVICE_BROKER_0 }}:$KAFKA_SERVICE_PORT_0,${{ steps.set_brokers.outputs.KAFKA_SERVICE_BROKER_1 }}:$KAFKA_SERVICE_PORT_1,${{ steps.set_brokers.outputs.KAFKA_SERVICE_BROKER_2 }}:$KAFKA_SERVICE_PORT_2 }}"]'