#COMMENT TEST 6
name: vdjerek_testing
on:
  pull_request:
    branches: ['*']
  issue_comment:
    types: [created]


jobs:
  beam_PreCommit_Go_vdjerek_test:
        runs-on: [self-hosted, ubuntu-20.04, vdjerek-test]
        name: beam_PreCommit_Go_vdjerek_test
        steps:       
          - name: Git checkout
            uses: actions/checkout@v3
          - name: debug
            run: env
          - name: run goPreCommit script
            run: ./gradlew :goPreCommit