name: Precommit Python Auto Formatter
run-name: Python Auto Formatter
on:
  pull_request:
    branches: [ "master", "release-*" ]
    paths: [ "sdks/python/apache_beam/.*"]
  issue_comment:
    types: [created, edited]


jobs:
  PythonAutoFormatter:
    if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run PythonFormatter PreCommit'}} || ${{github.event.schedule == '* */6 * * *'}}
    runs-on: [self-hosted, ubuntu-20.04]


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run:  pip install --retries 10 --upgrade pip && ls && pwd && pip install --retries 10 --upgrade tox==3.20.1 -r ./build-requirements.txt
        working-directory: sdks/python
      - name: Run python Lint 
        run: tox -e py3-yapf-check
        working-directory: sdks/python
