name: Precommit Portable Python
run-name: Portable Python Precommit
on:
  pull_request:
    branches: [ "master", "release-*" ]
    paths: [ 'model/.*', 'runners/core-construction-java/.*', 'runners/core-java/.*', 'runners/extensions-java/.*', 'runners/flink/.*', 'runners/java-fn-execution/.*', 'runners/reference/.*$', 'sdks/python/.*', 'release/.*' ]
  issue_comment:
    types: [created]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  PortablePythonPrecommit:
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.8', '3.10']
    if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Portable_Python PreCommit'}} || ${{github.event.schedule == '* */6 * * *'}}
    runs-on: ['self-hosted', Linux]

    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3.8.0
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python_version}}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
      - name: Install Go
        uses: actions/setup-go@v3
        with:
            go-version: '1.20'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: run Portable Python script
        run: PY_VER=${{ matrix.python_version }} ; ./gradlew :sdks:python:test-suites:portable:py${PY_VER//.}:preCommitPy${PY_VER//.}
