name: Precommit Python Lint 
run-name: Python Precommit Lint
on:
  pull_request:
    branches: [ "master", "release-*" ]
    paths: [ "model/.*","sdks/python/.*","release/.*"]
  issue_comment:
    types: [created, edited]


jobs:
  PythonDocker:
    if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Python_Lint PreCommit'}} || ${{github.event.schedule == '* */6 * * *'}}
    runs-on: [self-hosted, ubuntu-20.04]
    defaults:
      run:
        working-directory: sdks/python
    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3.8.0
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-go@v4
        with:
          go-version: '1.16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
      - name: run PythonLintPrecommit script
        run: ./gradlew :pythonLintPreCommit
