<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
name: Precommit Python coverage
run-name: Python Precommit coverage
on:
  pull_request:
    branches: [ "master", "release-*" ]
    paths: [ "model/.*", "sdks/python/.*", "sdks/python/.*"]
  issue_comment:
    types: [created, edited]


jobs:
  PythonCoverage:
    if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Python_Coverage PreCommit'}} || ${{github.event.schedule == '* */6 * * *'}}
    runs-on: [self-hosted, ubuntu-20.04]
    defaults:
      run:
        working-directory: sdks/python


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run:  pip install --retries 10 --upgrade pip && ls && pwd && pip install --retries 10 --upgrade tox==3.20.1 -r ./build-requirements.txt
        working-directory: sdks/python
      - name: Run python cloud coverage
        run: tox -e py38-cloudcoverage
        working-directory: sdks/python
      - name: Run python pyarrow
        run: tox -e py38-pyarrow-5
        working-directory: sdks/python
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: python-code-coverage-report
          path: "**/pytest*.xml"
