name: Precommit Python Runners
run-name: Python Precommit Runners
on:
  pull_request:
    branches: [ "master", "release-*" ]
    paths: [ "model/.*","sdks/python/.*", "release/.*" ]
  issue_comment:
    types: [created, edited]


jobs:
  PrecommitRunners:
    if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Python_Runners PreCommit'}} || ${{github.event.schedule == '* */6 * * *'}}
    runs-on: [self-hosted, ubuntu-20.04]
    defaults:
      run:
        working-directory: sdks/python


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7 - 3.11'
      - name: Install Dependencies
        run:  pip install --retries 10 --upgrade pip && ls && pwd && pip install --retries 10 --upgrade tox==3.20.1 -r ./build-requirements.txt
        working-directory: sdks/python
      - name: Run python cloud 
        run: tox -e py37-cloud py39-cloud py310-cloud py311-cloud -- apache_beam/runners/
        working-directory: sdks/python
      - name: Run mypy
        run: tox -e py37-cython py38-cython py39-cython py310-cython py311-cython -- apache_beam/runners/
        working-directory: sdks/python
