#    Licensed to the Apache Software Foundation (ASF) under one
#    or more contributor license agreements.  See the NOTICE file
#    distributed with this work for additional information
#    regarding copyright ownership.  The ASF licenses this file
#    to you under the Apache License, Version 2.0 (the
#    "License"); you may not use this file except in compliance
#    with the License.  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

name: PreCommit Community Metrics

on:
  push:
    tags: ['v*']
    branches: ['master', 'release-*']
  pull_request:
#   branches: [ "master", "release-*" ]
    branches: ['—Åommunity-metrics']
    paths: ['.test-infra/metrics/**']
  issue_comment:
    types: [created]
#  schedule:
#    - cron: '* */6 * * *'

jobs:
  CommunityMetricsPrecommit:
    name: Community Metrics
    runs-on: ['self-hosted', ubuntu-20.04 ]
    if: github.event_name == 'push'|| github.event_name == 'pull_request'|| github.event_name == 'schedule'|| github.event.comment.body == 'Run CommunityMetrics PreCommit'

    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: run Community Metrics Precommit script
        run: ./gradlew :communityMetricsPreCommit